package sistem.tampilan;

import GalbertoTuwondila.Source.Image.ImageFile;
import GalbertoTuwondila.Source.Image.ImagePreview;
import java.io.File;
import java.io.FileInputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hwpf.HWPFDocument;
import org.apache.poi.hwpf.extractor.WordExtractor;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;

/**
 *
 * @author compaq
 */
public class SuratMasuk extends javax.swing.JFrame {

    Connection cn = null;
    ResultSet rssumas = null;
    DefaultTableModel tabModel;
    int a = 0;
    private String dir;
    private JFileChooser fileChooser;
    private String filePath = null;
    private File file;
    private POIFSFileSystem fs = null;
    private FileInputStream fis;
    private HWPFDocument doc;
    private WordExtractor we;
    String[] paragraphs;

    public SuratMasuk() {
        initComponents();
        konek();
        tampilData();
        initAbstract();

    }

    private void initAbstract() {
        setLocationRelativeTo(null);
        txtHasil.setLineWrap(true);
        txtHasil.setWrapStyleWord(true);
        fileChooser = new JFileChooser();

    }

    void konek() {
        try {
            //aktif driver
            Class.forName("com.mysql.jdbc.Driver");
            //konek database
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/surat", "root", "");
            Object[] judul_kolom = {"Id Surat", "Nomor Surat", "Tanggal Surat", "Tanggal Terima", "Pengirim Surat", "Perihal Surat", "Disposisi", "Tahun", " File Surat"};
            tabModel = new DefaultTableModel(null, judul_kolom);
            tab_sumas.setModel(tabModel);
            //       tampilData();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void tampilData() {
        try {
            Statement stm; //buat stm
            stm = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            rssumas = stm.executeQuery("select * from surat_masuk");
            while (rssumas.next()) {
                Object[] data = {rssumas.getString("id_surat"),
                    rssumas.getString("no_surat"),
                    rssumas.getDate("tgl_surat"),
                    rssumas.getDate("tgl_surat_diterima"),
                    rssumas.getString("pengirim"),
                    rssumas.getString("prihal_surat"),
                    rssumas.getString("disposisi"),
                    rssumas.getString("tahun"),
                    rssumas.getString("file_surat")
                };
                tabModel.addRow(data);
            }

        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    void kosongkanform() {
        id_surat.setText("");
        no_surat.setText("");
        tgl_surat.setDate(null);
        tgl_surat_terima.setText("");
        pengirim_surat.setText("");
        prihal_surat.setText("");
        disposisi.setText("");
        thn.setText("");
        txtDir.setText("");
        txtHasil.setText("");
        tanggalsrt.setText("");
        tgl_surat1.setDate(null);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id_surat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        no_surat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tgl_surat_terima = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        prihal_surat = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        disposisi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        carfil = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        carsu = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        pengirim_surat = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tab_sumas = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        thn = new javax.swing.JTextField();
        tgl_surat = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHasil = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        tanggalsrt = new javax.swing.JTextField();
        tgl_surat1 = new com.toedter.calendar.JDateChooser();
        crpengirim = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        crperihal = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Pemberkasan Surat Kementerian Agama Purwokerto");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 102, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("SISTEM PEMBERKASAN SURAT MASUK DAN SURAT KELUAR");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("KEMENTERIAN AGAMA KABUPATEN BANYUMAS PURWOKERTO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Data-Data Surat Masuk");

        jLabel4.setText("Id Surat");

        jLabel5.setText("Nomor Surat");

        no_surat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_suratActionPerformed(evt);
            }
        });

        jLabel6.setText("Tanggal Surat");

        jLabel7.setText("Pengirim Surat");

        jLabel8.setText("Perihal Surat");

        prihal_surat.setColumns(20);
        prihal_surat.setRows(5);
        jScrollPane2.setViewportView(prihal_surat);

        jLabel9.setText("Disposisi");

        disposisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disposisiActionPerformed(evt);
            }
        });

        jLabel10.setText("File Surat");

        txtDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirActionPerformed(evt);
            }
        });

        carfil.setText("Cari File");
        carfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carfilActionPerformed(evt);
            }
        });

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        carsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                carsuKeyPressed(evt);
            }
        });

        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel11.setText("Tanggal Terima Surat");

        tab_sumas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Surat", "Nomor Surat", "Tanggal Surat", "Tanggal Terima ", "Pengirim Surat", "Perihal Surat", "Disposisi", "Tahun", "File Surat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_sumas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_sumasMouseClicked(evt);
            }
        });
        tab_sumas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tab_sumasComponentShown(evt);
            }
        });
        jScrollPane3.setViewportView(tab_sumas);

        jLabel12.setText("Tahun");

        tgl_surat.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgl_suratPropertyChange(evt);
            }
        });

        txtHasil.setColumns(20);
        txtHasil.setRows(5);
        jScrollPane1.setViewportView(txtHasil);

        jButton5.setText("Baca File Surat");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tgl_surat1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgl_surat1PropertyChange(evt);
            }
        });

        crpengirim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                crpengirimKeyPressed(evt);
            }
        });

        crperihal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                crperihalKeyPressed(evt);
            }
        });

        jRadioButton1.setText("Cari Berdasarkan Nomor Surat");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        jRadioButton2.setText("Cari Berdasarkan Pengirim Surat");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        jRadioButton3.setText("Cari Berdasarkan Perihal  Surat");
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(338, 338, 338))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(69, 69, 69)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(disposisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pengirim_surat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(tgl_surat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tgl_surat_terima, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(tgl_surat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tanggalsrt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(no_surat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(id_surat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(122, 122, 122)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(159, 159, 159))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(carfil)
                                        .addGap(3, 3, 3))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addComponent(jScrollPane3)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(crperihal, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(carsu)
                                    .addComponent(crpengirim))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3)
                        .addGap(128, 128, 128)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_surat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(56, 56, 56))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(no_surat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(carfil)
                                    .addComponent(jLabel5))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tgl_surat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tanggalsrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tgl_surat_terima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl_surat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(pengirim_surat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(disposisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(carsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crpengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(crperihal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Statement stm = cn.createStatement();
            a = stm.executeUpdate("insert into surat_masuk set id_surat='" + id_surat.getText() + "',"
                    + "no_surat='" + no_surat.getText() + "',"
                    + "tgl_surat='" + tanggalsrt.getText() + "',"
                    + "tgl_surat_diterima='" + tgl_surat_terima.getText() + "',"
                    + "pengirim='" + pengirim_surat.getText() + "',"
                    + "prihal_surat='" + prihal_surat.getText() + "',"
                    + "disposisi='" + disposisi.getText() + "',"
                    + "tahun='" + thn.getText() + "',"
                    + "file_surat='" + txtDir.getText() + "'");
            tampilData();
            kosongkanform();
        } catch (Exception e) {
            e.printStackTrace();
        }
        if (a != 0) {
            JOptionPane.showMessageDialog(null, "DATA TERSIMPAN");
        } else {
            JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN \n Cek Id Jangan Sampai Terjadi Duplikat Id \n Silahkan Coba Lagi");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {

            Statement stm = cn.createStatement();
            a = stm.executeUpdate("delete from surat_masuk where id_surat='"
                    + tabModel.getValueAt(tab_sumas.getSelectedRow(), 0) + "'");
            tampilData();
            kosongkanform();
        } catch (Exception e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "DATA TERHAPUS");

    }//GEN-LAST:event_jButton2ActionPerformed
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Statement stm = cn.createStatement();
            a = stm.executeUpdate("update surat_masuk set id_surat='" + id_surat.getText() + "',"
                    + "no_surat='" + no_surat.getText() + "',"
                    + "tgl_surat='" + tanggalsrt.getText() + "',"
                    + "tgl_surat_diterima='" + tgl_surat_terima.getText() + "',"
                    + "pengirim='" + pengirim_surat.getText() + "',"
                    + "prihal_surat='" + prihal_surat.getText() + "',"
                    + "disposisi='" + disposisi.getText() + "',"
                    + "tahun='" + thn.getText() + "',"
                    + "file_surat='" + txtDir.getText() + "'where id_surat='"
                    + tabModel.getValueAt(tab_sumas.getSelectedRow(), 0) + "'");
            tampilData();
            kosongkanform();
        } catch (Exception e) {
            e.printStackTrace();
        }
        if (a == 0) {
            JOptionPane.showMessageDialog(null, "DATA GAGAL DI-UPDATE \n Silahkan Coba Lagi");
        } else {
            JOptionPane.showMessageDialog(null, "DATA TER-UPDATE");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new MenuUtama().show();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void carfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carfilActionPerformed
        if (JFileChooser.APPROVE_OPTION == fileChooser.showOpenDialog(this)) {
            filePath = fileChooser.getSelectedFile().getAbsolutePath();
            file = new File(filePath);
            txtDir.setText(filePath);
            txtHasil.setText("");
        }


    }//GEN-LAST:event_carfilActionPerformed

    private void tab_sumasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_sumasMouseClicked
        id_surat.setText(tabModel.getValueAt(tab_sumas.getSelectedRow(), 0) + "");
        no_surat.setText(tabModel.getValueAt(tab_sumas.getSelectedRow(), 1) + "");
        tanggalsrt.setText(tabModel.getValueAt(tab_sumas.getSelectedRow(), 2) + "");
        tgl_surat_terima.setText(tabModel.getValueAt(tab_sumas.getSelectedRow(), 3) + "");
        pengirim_surat.setText(tabModel.getValueAt(tab_sumas.getSelectedRow(), 4) + "");
        prihal_surat.setText(tabModel.getValueAt(tab_sumas.getSelectedRow(), 5) + "");
        disposisi.setText(tabModel.getValueAt(tab_sumas.getSelectedRow(), 6) + "");
        thn.setText(tabModel.getValueAt(tab_sumas.getSelectedRow(), 7) + "");
        txtDir.setText(tabModel.getValueAt(tab_sumas.getSelectedRow(), 8) + "");

    }//GEN-LAST:event_tab_sumasMouseClicked

    private void carsuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carsuKeyPressed
        // TODO add your handling code here:
        cari_nama_user();
    }//GEN-LAST:event_carsuKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        JFrame form = new JFrame();
        form.setSize(800, 700);
        new tengah(this);
    }//GEN-LAST:event_formWindowActivated

    private void no_suratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_suratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_suratActionPerformed

    private void disposisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disposisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disposisiActionPerformed

    private void txtDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (filePath != null) {

            Thread t = new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        fis = new FileInputStream(file);
                        doc = new HWPFDocument(fis);
                        we = new WordExtractor(doc);
                        //get Paragraph text  as array
                        paragraphs = we.getParagraphText();

                        for (int i = 0; i < paragraphs.length; i++) {
                            //paragraphs[i] = paragraphs[i].replaceAll("\\cM?\r?\n","");
                            txtHasil.append(paragraphs[i]);
                        }
                    } catch (Exception exc) {
                        System.out.println(exc.getMessage());
                    } finally {
                    }
                }
            });
            t.start();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tgl_suratPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgl_suratPropertyChange
        // TODO add your handling code here:
        if (tgl_surat.getDate() != null) {
            SimpleDateFormat Format = new SimpleDateFormat("yyyy-MM-dd");
            String tanggalSurat = Format.format(tgl_surat.getDate());
            tanggalsrt.setText(tanggalSurat);

        }
    }//GEN-LAST:event_tgl_suratPropertyChange

    private void tgl_surat1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgl_surat1PropertyChange
        if (tgl_surat1.getDate() != null) {
            SimpleDateFormat Format = new SimpleDateFormat("yyyy-MM-dd");
            String tanggalSurat = Format.format(tgl_surat1.getDate());
            tgl_surat_terima.setText(tanggalSurat);
        }
    }//GEN-LAST:event_tgl_surat1PropertyChange

    private void crpengirimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_crpengirimKeyPressed
        Object[] Baris = {"Id Surat", "Nomor Surat", "Tanggal Surat", "Tanggal Terima", "Pengirim Surat", "Perihal Surat", "Disposisi", "Tahun", " File Surat"};
        tabModel = new DefaultTableModel(null, Baris);
        tab_sumas.setModel(tabModel);

        //panggil method koneksi
        // java.sql.Connection conn = new DBConnection().connect();

        //untuk menampilkan di table
        try {
            String sql = "select * from surat_masuk where pengirim like '%" + crpengirim.getText() + "%'";
            java.sql.Statement stmt = cn.createStatement();
            java.sql.ResultSet rslt = stmt.executeQuery(sql);
            while (rslt.next()) {
                String id = rslt.getString("id_surat");
                String no = rslt.getString("no_surat");
                String tgl_surat = rslt.getString("tgl_surat");
                String tgl_surat_terima = rslt.getString("tgl_surat_diterima");
                String pengirim = rslt.getString("pengirim");
                String prihal = rslt.getString("prihal_surat");
                String dis = rslt.getString("disposisi");
                String thn = rslt.getString("tahun");
                String file = rslt.getString("file_surat");

                String[] dataField = {id, no, tgl_surat, tgl_surat_terima, pengirim, prihal, dis, thn, file};
                tabModel.addRow(dataField);
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_crpengirimKeyPressed

    private void crperihalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_crperihalKeyPressed
        Object[] Baris = {"Id Surat", "Nomor Surat", "Tanggal Surat", "Tanggal Terima", "Pengirim Surat", "Perihal Surat", "Disposisi", "Tahun", " File Surat"};
        tabModel = new DefaultTableModel(null, Baris);
        tab_sumas.setModel(tabModel);

        try {
            String sql = "select * from surat_masuk where prihal_surat like '%" + crperihal.getText() + "%'";
            java.sql.Statement stmt = cn.createStatement();
            java.sql.ResultSet rslt = stmt.executeQuery(sql);
            while (rslt.next()) {
                String id = rslt.getString("id_surat");
                String no = rslt.getString("no_surat");
                String tgl_surat = rslt.getString("tgl_surat");
                String tgl_surat_terima = rslt.getString("tgl_surat_diterima");
                String pengirim = rslt.getString("pengirim");
                String prihal = rslt.getString("prihal_surat");
                String dis = rslt.getString("disposisi");
                String thn = rslt.getString("tahun");
                String file = rslt.getString("file_surat");

                String[] dataField = {id, no, tgl_surat, tgl_surat_terima, pengirim, prihal, dis, thn, file};
                tabModel.addRow(dataField);
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_crperihalKeyPressed

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        carsu.getKeyListeners();
        carsu.setVisible(true);
        crpengirim.setVisible(false);
        crperihal.setVisible(false);

    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        crpengirim.getKeyListeners();
        carsu.setVisible(false);
        crpengirim.setVisible(true);
        crperihal.setVisible(false);
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseClicked
        crperihal.getKeyListeners();
        carsu.setVisible(false);
        crpengirim.setVisible(false);
        crperihal.setVisible(true);
    }//GEN-LAST:event_jRadioButton3MouseClicked

    private void tab_sumasComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tab_sumasComponentShown
        try {
            RowId.class
                    .getField("Id Surat");
        } catch (NoSuchFieldException ex) {
            Logger.getLogger(SuratMasuk.class
                    .getName()).log(Level.SEVERE, null, ex);
        } catch (SecurityException ex) {
            Logger.getLogger(SuratMasuk.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tab_sumasComponentShown

    public void cari_nama_user() {
        Object[] Baris = {"Id Surat", "Nomor Surat", "Tanggal Surat", "Tanggal Terima", "Pengirim Surat", "Perihal Surat", "Disposisi", "Tahun", " File Surat"};
        tabModel = new DefaultTableModel(null, Baris);
        tab_sumas.setModel(tabModel);

        //panggil method koneksi
        // java.sql.Connection conn = new DBConnection().connect();

        //untuk menampilkan di table
        try {
            String sql = "select * from surat_masuk where no_surat like '%" + carsu.getText() + "%'";
            java.sql.Statement stmt = cn.createStatement();
            java.sql.ResultSet rslt = stmt.executeQuery(sql);
            while (rslt.next()) {
                String id = rslt.getString("id_surat");
                String no = rslt.getString("no_surat");
                String tgl_surat = rslt.getString("tgl_surat");
                String tgl_surat_terima = rslt.getString("tgl_surat_diterima");
                String pengirim = rslt.getString("pengirim");
                String prihal = rslt.getString("prihal_surat");
                String dis = rslt.getString("disposisi");
                String thn = rslt.getString("tahun");
                String file = rslt.getString("file_surat");

                String[] dataField = {id, no, tgl_surat, tgl_surat_terima, pengirim, prihal, dis, thn, file};
                tabModel.addRow(dataField);
            }
        } catch (Exception ex) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuratMasuk().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carfil;
    private javax.swing.JTextField carsu;
    private javax.swing.JTextField crpengirim;
    private javax.swing.JTextField crperihal;
    private javax.swing.JTextField disposisi;
    private javax.swing.JTextField id_surat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField no_surat;
    private javax.swing.JTextField pengirim_surat;
    private javax.swing.JTextArea prihal_surat;
    private javax.swing.JTable tab_sumas;
    private javax.swing.JTextField tanggalsrt;
    private com.toedter.calendar.JDateChooser tgl_surat;
    private com.toedter.calendar.JDateChooser tgl_surat1;
    private javax.swing.JTextField tgl_surat_terima;
    private javax.swing.JTextField thn;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextArea txtHasil;
    // End of variables declaration//GEN-END:variables
}
